# serverless.yml
component: http # (必选) 组件名称
name: inyaa-sakura # 必选) 组件实例名称.

inputs:
  region: ap-shanghai # 云函数所在区域
  src: # 部署src下的文件代码，并打包成zip上传到bucket上
    src: ./.output # 本地需要打包的文件目录
  faas: # 函数配置相关
    framework: express #选择框架，此处以 express 为例
    runtime: Nodejs16.13
    name: inyaa-sakura # 云函数名称
    timeout: 10 # 超时时间，单位秒
    memorySize: 512 # 内存大小，默认 512 MB
  apigw: #  # http 组件会默认帮忙创建一个 API 网关服务
    isDisabled: false # 是否禁用自动创建 API 网关功能
    id: api-gjwkb7bb # api网关服务ID，不填则自动新建网关
    name: serverless # api网关服务ID
    api: # 创建的 API 相关配置
      cors: true #  允许跨域
      timeout: 15 # API 超时时间
      name: apiName # API 名称
      qualifier: $DEFAULT # API 关联的版本
    protocols:
      - http
      - https
    environment: release
    # 自定义域名相关配置
    customDomains:
      - domain: csf.inyaa.cn
        certificateId: tkqlKpga # 证书 ID
        protocols:
            - https